import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Nav from "./components/Nav";
import styles from "./layout.module.css";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          // inter.className
          // back tick
          `${styles.page} ${inter.className}`
        }
      >
        <Providers>
          <Nav />
          <div className={styles.pageContent}>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
